Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Style/Documentation:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/DotPosition:
  EnforcedStyle: leading

Style/DoubleNegation:
  Enabled: false
